site_name: nodejs-dev-x03
site_description: 
repo_url: https://github.com/rhdh-skitamura-org/nodejs-dev-x03-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

theme:
  name: material
  font:
    text:
      - "Arial"
      - "Helvetica"
      - "sans-serif"

# Note for content editors, edit only the section below
nav:
  - nodejs-dev-x03 Documentation: index.md
